import styles from "@/app/main/layout.module.css";
import Header from "@/components/common/header/main";
import Sidebar from "@/components/common/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Turbo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Turbo | Main</title>
      </Head>
      <body className={[inter.className, styles.body].join(" ")}>
        <Header />
        <main className={styles.main}>
          <Sidebar />
          <div className={styles.mainContent}>{children}</div>
        </main>
      </body>
    </html>
  );
}

export const dynamic = "error";
