version: '3'
services:
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_DATABASE=todo_golang_development
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
