name: Frontend Pipeline
run-name: Frontend Pipeline

on: [push]

jobs:
  fe-pipeline:
    name: Frontend Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/core
    steps:
      - uses: actions/checkout@v4
      - name: Setup frontend/core
        uses: ./.github/actions/setup-node-project
        with:
          node-version: '20.x'
          working-directory: ./frontend/core
          cache-dependency-path: ./frontend/core/package-lock.json
      - name: Lint
        run: npm run lint
      - name: Compile
        run: npm run tsc
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
